<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRyKZpZD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRyKZpZD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRyKZpZD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRyKZpZD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRyKZpZD\App_KernelDevDebugContainer([
    'container.build_hash' => 'RyKZpZD',
    'container.build_id' => 'b3b83040',
    'container.build_time' => 1707648446,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRyKZpZD');
